function [Y,Xf,Af] = nfunction(X,~,~)
%NFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 02-Mar-2015 23:49:11.
% 
% [Y] = nfunction(X,~,~) takes these arguments:
% 
%   X = 0xTS cell, 0 inputs over TS timsteps
% 
% and returns:
%   Y = 0xTS cell of 0 outputs over TS timesteps.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

  % ===== NEURAL NETWORK CONSTANTS =====
  
  
  % ===== SIMULATION ========
  
  % Format Input Arguments
  isCellX = iscell(X);
  if ~isCellX, X = {X}; end;
  
  % Dimensions
  TS = size(X,2); % timesteps
  
  % Allocate Outputs
  Y = cell(0,TS);
  
  % Time loop
  for ts=1:TS
  
  end
  
  % Final Delay States
  Xf = cell(0,0);
  Af = cell(0,0);
  
  % Format Output Arguments
  if ~isCellX, Y = cell2mat(Y); end
end

% ===== MODULE FUNCTIONS ========

